inputs_dir = 'outputs';
output_dir = 'outputs_ssor-pcg_figs';

inputs = dir(fullfile(inputs_dir,'**','*.mat'));
inputs = inputs(~[inputs.isdir]); % inputs.name を使う
n_files = length(inputs);

for i = 1:n_files
    load(fullfile(inputs(i).folder, inputs(i).name));
    plot_conv_hist(convergence, metadata.matrix_name, ...
        'show_plot', false, ...
        'save_fig', true, ...
        'save_fig_filename', strcat(inputs(i).name), ...
        'format_type', ["svg", "fig"], ...
        'output_dir', output_dir)
end
